export const Governorates = [
  { label: "القاهرة" },
  { label: "الجيزة" },
  { label: "الإسكندرية" },
  { label: "الدقهلية" },
  { label: "البحر الأحمر" },
  { label: "البحيرة" },
  { label: "الغربية" },
  { label: "بورسعيد" },
  { label: "السويس" },
  { label: "الإسماعيلية" },
  { label: "كفر الشيخ" },
  { label: "الشرقية" },
  { label: "القليوبية" },
  { label: "دمياط" },
  { label: "مطروح" },
  { label: "المنيا" },
  { label: "بني سويف" },
  { label: "الفيوم" },
  { label: "المنوفية" },
  { label: "turky" },
  { label: "الأقصر" },
  { label: "أسيوط" },
  { label: "سوهاج" },
  { label: "قنا" },
  { label: "أسوان" },
  { label: "شمال سيناء" },
  { label: "جنوب سيناء" },
  { label: "الوادي الجديد" }
];
